# Generated by Django 5.1.2 on 2024-10-14 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('UGZ', 'Ugz'), ('INN', 'Innet'), ('MET', 'Meteoblue'), ('AWE', 'Awel')], default='UGZ', max_length=3)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('wgs84_lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('wgs84_lon', models.DecimalField(decimal_places=5, max_digits=7)),
                ('masl', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('magl', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('sensor_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sensor_serial', models.CharField(max_length=100, unique=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=20)),
                ('interval_s', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(default='', max_length=512)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logger')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meas_type', models.CharField(choices=[('ws_ms', 'Wind Speed Ms'), ('ws_max_ms', 'Wind Speed Max Ms'), ('e_ws_ms', 'East Wind Speed Ms'), ('n_ws_ms', 'North Wind Speed Ms'), ('h_pct', 'Humidity Pct'), ('irr_wm2', 'Irradiation Wm2'), ('w_dir_deg', 'Wind Direction Deg'), ('p_hpa', 'Pressure Hpa'), ('t_c', 'Temperature C'), ('bat_v', 'Battery Voltage V')], max_length=16)),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.installation')),
            ],
        ),
    ]
