# Generated by Django 4.2.16 on 2024-10-24 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(default="", max_length=128)),
                (
                    "manufacturer_url",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "datasheet",
                    models.FileField(
                        blank=True, null=True, upload_to="device-datasheets/"
                    ),
                ),
                (
                    "user_manual",
                    models.FileField(
                        blank=True, null=True, upload_to="device-user_manual/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="device-attachments/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="device-images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_s",
                    models.IntegerField(
                        default=600,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=512)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="installation-images/"
                    ),
                ),
                (
                    "magl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(max_length=128, unique=True)),
                (
                    "sensor_serial",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "organization",
                    models.CharField(
                        choices=[
                            ("UGZ", "Umwelt- und Gesundheitsschutz Zürich"),
                            ("INN", "INNET"),
                            ("MET", "Meteoblue"),
                            ("AWE", "Amt für Abfall, Wasser, Energie und Luft"),
                        ],
                        default="UGZ",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loggers",
                        to="api.devicemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        choices=[
                            ("UGZ", "Umwelt- und Gesundheitsschutz Zürich"),
                            ("INN", "INNET"),
                            ("MET", "Meteoblue"),
                            ("AWE", "Amt für Abfall, Wasser, Energie und Luft"),
                        ],
                        default="UGZ",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("wgs84_lat", models.DecimalField(decimal_places=5, max_digits=7)),
                ("wgs84_lon", models.DecimalField(decimal_places=5, max_digits=7)),
                (
                    "masl",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meas_type",
                    models.CharField(
                        choices=[
                            ("ws_ms", "wind speed, ms^-1"),
                            ("ws_max_ms", "max wind , ms^-1"),
                            ("e_ws_ms", "east wind speed, ms^-1"),
                            ("n_ws_ms", "north wind speed, ms^-1"),
                            ("rel_h_pct", "humidity, percent"),
                            ("irr_wm2", "irradiation wm^-2"),
                            ("w_dir_deg", "wind direction, degrees"),
                            ("atm_p_hpa", "pressure, hPa"),
                            ("air_t_c", "temperature, C"),
                            ("bat_v", "battery, V"),
                            ("precip_mm", "precipitation, 10^-3m"),
                            ("dewpoint_t_c", "Dew Point, C"),
                            ("global_rad_wm2", "Solar Irradiation, Wm^-2"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=5, max_digits=10)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="api.installation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoggerAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UGZ", "Umwelt- und Gesundheitsschutz Zürich"),
                            ("INN", "INNET"),
                            ("MET", "Meteoblue"),
                            ("AWE", "Amt für Abfall, Wasser, Energie und Luft"),
                        ],
                        default="UGZ",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logger_actions",
                        to="api.logger",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="installation",
            name="logger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="api.logger",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="api.site",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="api.technician",
            ),
        ),
    ]
