# Generated by Django 4.2.16 on 2024-10-17 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("datasheet", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technician", models.CharField(max_length=20)),
                (
                    "interval_s",
                    models.IntegerField(
                        default=600,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.CharField(default="", max_length=512)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("UGZ", "Umwelt- und Gesundheitsschutz Zürich"),
                            ("INN", "INNET"),
                            ("MET", "Meteoblue"),
                            ("AWE", "Amt für Abfall, Wasser, Energie und Luft"),
                        ],
                        default="UGZ",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("wgs84_lat", models.DecimalField(decimal_places=5, max_digits=7)),
                ("wgs84_lon", models.DecimalField(decimal_places=5, max_digits=7)),
                (
                    "masl",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "magl",
                    models.DecimalField(
                        decimal_places=1,
                        default=None,
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meas_type",
                    models.CharField(
                        choices=[
                            ("ws_ms", "wind speed, ms^-1"),
                            ("ws_max_ms", "max wind , ms^-1"),
                            ("e_ws_ms", "east wind speed, ms^-1"),
                            ("n_ws_ms", "west wind speed, ms^-1"),
                            ("h_pct", "humidity, percent"),
                            ("irr_wm2", "irradiation wm^-2"),
                            ("w_dir_deg", "wind direction, degrees"),
                            ("p_hpa", "pressure, hPa"),
                            ("t_c", "temperature, C"),
                            ("bat_v", "battery, V"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=5, max_digits=10)),
                ("timestamp", models.DateTimeField()),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.installation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "sensor_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("sensor_serial", models.CharField(max_length=100, unique=True)),
                (
                    "device_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.devicemodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="installation",
            name="logger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.logger"
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.site"
            ),
        ),
    ]
