# Generated by Django 4.2.16 on 2024-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="meas_type",
            field=models.CharField(
                choices=[
                    ("ws_ms", "wind speed, ms^-1"),
                    ("ws_max_ms", "max wind , ms^-1"),
                    ("e_ws_ms", "east wind speed, ms^-1"),
                    ("n_ws_ms", "north wind speed, ms^-1"),
                    ("rel_h_pct", "humidity, percent"),
                    ("irr_wm2", "irradiation wm^-2"),
                    ("w_dir_deg", "wind direction, degrees"),
                    ("atm_p_hpa", "pressure, hPa"),
                    ("air_t_c", "temperature, C"),
                    ("bat_v", "battery, V"),
                    ("precip_mm", "precipitation, 10^-3m"),
                    ("dewpoint_t_c", "Dew Point, C"),
                    ("global_rad_wm2", "Solar Irradiation, Wm^-2"),
                ],
                max_length=16,
            ),
        ),
    ]
