# Generated by Django 5.1.2 on 2024-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="datasheet",
            field=models.CharField(default="", max_length=100),
        ),
    ]
