services:
  backend:
    image: "python:3.12-bookworm"
    container_name: sk-backend
    working_dir: /usr/src/
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: "/usr/src/entry-point.sh"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./backend/:/usr/src/
    networks:
      - sk-net

  frontend:
    image: "node:22-alpine"
    container_name: sk-frontend
    working_dir: /home/node/
    user: "node"
    ports:
      - ${VITE_PORT:-3000}:${VITE_PORT:-3000}
    depends_on:
      - backend
    command: sleep infinity
    volumes:
      - ./frontend/:/home/node
      - ./frontend/dist:/home/node/dist/:rw
    networks:
      - sk-net

  db: # local storage
    container_name: sk-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sk-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-sk-db}
      POSTGRES_HOST: ${POSTGRES_HOST:-sk-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - sk-db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - sk-net

volumes:
  sk-db-data:
    driver: local

networks:
  sk-net:
    name: sk-network
    driver: bridge
