"""add interval to loggers

Revision ID: 51ab1a316ada
Revises: d135996a22b5
Create Date: 2024-09-15 15:02:53.016530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ab1a316ada'
down_revision: Union[str, None] = 'd135996a22b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logger', sa.Column('interval_s', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logger', 'interval_s')
    # ### end Alembic commands ###
